export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const LOADING_CONVERSATIONS = 'LOADING_CONVERSATIONS';