export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const STOP_LOADING = 'STOP_LOADING';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const LOADING_CONVERSATIONS = 'LOADING_CONVERSATIONS';
export const SET_SOCKET = 'SET_SOCKET';